### ISSUE TITLE
Identify stackers using numerical ID.

### ISSUE THREAD

**Issue by LNow** [citycoins/citycoin#107]
In order to reduce execution costs of stacking and claiming stacking reward each stacker (principal) should have its own numerical ID.

By doing so we reduce the amount of data being written and read during stacking/claiming stacking reward operations.

It can and probably should be merged with miners identification logic. As a result we'll have a one list of users identified by their numerical ID's.

**Comment by SyAsteria** [comment]
what about we use BNS usernames instead?

**Comment by whoabuddy** [comment]
The usernames can vary in length, and the goal here is to reduce the execution cost by making the value we use for lookup as small as possible. We found with mining functions that if we use an ID as a reference it's much cheaper than trying to use the full on principal (or something like a BNS username) for the operation.

**Comment by SyAsteria** [comment]
of course, but if we want to identify them aren't we gonna have to keep a sort of directory to map the numerical IDs to the addresses anyway? I'm probably wrong
