### ISSUE TITLE
[UI] Activity feed extends over the Dashboard square

### ISSUE THREAD

**Issue by 314159265359879** [citycoins/citycoin#140]
Tested on Firefox/Windows 10
![image](https://user-images.githubusercontent.com/33360391/128245981-d130b6ce-c2b8-4f0f-82f1-f5baa94bdcb6.png)

**Comment by whoabuddy** [comment]
Closing this out as it relates to the UI on minemiamicoin.com, if this is still a problem, please file a new issue at the link below!

https://github.com/miamicoin/ui
