### ISSUE TITLE
Deploy smart contract to check winning status for many (up to 200) blocks

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#141]
something simple like

```
(define-read-only (is-winner (bh uint))
  (contract-call? .city-coin-core-v1 is-block-winner tx-sender bh)))

(define-read-only (is-winner-many (block-heights (list 200 uint)))
  (map is-winner block-heights))
```

**Comment by LNow** [comment]
It's a great idea, but I'm afraid we gonna have same problem as #74 
That's the reason it is not implemented in our main contract.

So far we haven't found any reliable solution that would allow us execute complex read-only functions.

**Comment by friedger** [comment]
I see
