### ISSUE TITLE
How do i claim my rewards from mining miamicoin

### ISSUE THREAD

**Issue by hebertjonathan99** [citycoins/citycoin#142]
I sent some STX over to be mined. Here is the transaction id: 0x8246583e2c7527deba780031249b7b945e4207ef8ad8a018a4c1a278ccc9a01d

I dont see any coins being mined in my stx wallet. Not sure whats going on. Please help.

**Comment by friedger** [comment]
What is the expected outcome from that tx?

Looking at the contract (and docs) it says that you have a chance of around 1/50th to win the block reward

You can find out after 100 blocks whether you won or not.

I'll close the issue now as it works as expected. Let us know if the documentation is not clear.

**Comment by hebertjonathan99** [comment]
So if I loose will the Stx coins automatically be returned to my wallet?   Where do I check to see if I won and what block they are on?
I am new to mining so I expected to see some time of receipt showing that my 60stx were mining for miamicoin.



Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 1:30 PM, Friedger ***@***.***> wrote:   


Closed #142.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LNow** [comment]
@hebertjonathan99 STX used for mining won't be returned to your wallet at all.
As it is stated in our documentation:
> Mining CityCoins is performed by transferring Stacks (STX) tokens into the smart contract in a given Stacks block, **and is a one-way process. Once sent, the STX are committed to the contract and not returned.** 

https://docs.citycoins.co/citycoins-core-protocol/mining-citycoins#overview

You mined at blocks 24752-24756 and it looks like someone already claimed reward for all but 1 of these blocks.
![image](https://user-images.githubusercontent.com/829210/128775140-4d120505-8e52-4655-a907-f8c5ea522ad0.png)
![image](https://user-images.githubusercontent.com/829210/128775269-ccc7e6d7-1965-4d0e-ac48-3405eba08736.png)
![image](https://user-images.githubusercontent.com/829210/128775330-b57158b1-6e72-49e4-b1c5-f355f020ee42.png)
![image](https://user-images.githubusercontent.com/829210/128775647-b120525e-8532-4c80-adce-7b50562f8133.png)
![image](https://user-images.githubusercontent.com/829210/128775714-b26f9bcf-26aa-4223-a4bc-3d4175e47d42.png)

Please visit https://minemiamicoin.com/ , click on `Redeem` button and check if you are the one who can claim reward for block 24755 or not.

**Comment by hebertjonathan99** [comment]
I am confused.  If I loose the block what happens to my stx.  Do losers get any miamicoin?


Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 2:22 PM, ***@***.***> wrote:   


@hebertjonathan99 STX used for mining won't be returned to your wallet at all.
As it is stated in our documentation:


Mining CityCoins is performed by transferring Stacks (STX) tokens into the smart contract in a given Stacks block, and is a one-way process. Once sent, the STX are committed to the contract and not returned.


https://docs.citycoins.co/citycoins-core-protocol/mining-citycoins#overview

You mined at blocks 24752-24756 and it looks like someone already claimed reward for all but 1 of these blocks.






Please visit https://minemiamicoin.com/ , click on Redeem button and check if you are the one who can claim reward for block 24755 or not.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LNow** [comment]
Only block winners are eligible for MIA token.
If you want to find out more where your STX has been transferred, please read first page of our docs: https://docs.citycoins.co/. Everything is there.

**Comment by hebertjonathan99** [comment]
Thats doesn't answer my question and I dont think you all message this good enough. Can I get my stx back?

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 3:34 PM, ***@***.***> wrote:   


Only block winners are eligible for MIA token.
If you want to find out more where your STX has been transferred, please read first page of our docs: https://docs.citycoins.co/. Everything is there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LNow** [comment]
No you can't.
Look at my first reply: 
> (...)Once sent, the STX are committed to the contract and not returned.

**Comment by hebertjonathan99** [comment]
So since I lost the block bid.  I lose my stx tokens as well?


Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 4:15 PM, ***@***.***> wrote:   


No you can't.
Look at my first reply:


(...)Once sent, the STX are committed to the contract and not returned.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hebertjonathan99** [comment]
Can you answer my question?

Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 4:17 PM, Jonathan Hebert, ***@***.***> wrote:   So since I lost the block bid.  I lose my stx tokens as well?


Sent from Yahoo Mail on Android 
 
  On Mon, Aug 9, 2021 at 4:15 PM, ***@***.***> wrote:   


No you can't.
Look at my first reply:


(...)Once sent, the STX are committed to the contract and not returned.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LNow** [comment]
It has been answered few times.
You can't get your STX back, because they have been transferred to reserved wallet for city of Miami.

**Comment by hebertjonathan99** [comment]
So wtf is the purpose of bidding on Miami Coin if you loose the bid you loose your stx?  There is absolutely no benefit of bidding 
Don't worry wait until this is shared online and youtube with the crypto community.   This scam will be exposed!
Sent from Yahoo Mail on Android 
 
  On Fri, Aug 13, 2021 at 2:51 AM, ***@***.***> wrote:   


It has been answered few times.
You can't get your STX back, because they have been transferred to reserved wallet for city of Miami.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
