### ISSUE TITLE
Core contract v1 - stack-tokens-closure - unused variables

### ISSUE THREAD

**Issue by unclemantis** [citycoins/citycoin#160]
While tracing the CityCoins clarity contracts for a case study I discovered that 2 variables are defined and not referenced in the -core-v1.clar files across every copy in this repo.

This does not appear to be a priority and does not affect the operation of the contract.

Link to the lines are pasted below. Keep at it!

(https://github.com/citycoins/citycoin/blob/59dbb0c0cddcfb851da80b0a774f11fd3fa23afd/contracts/citycoin-core-v1.clar#L709-L710)

**Comment by whoabuddy** [comment]
Thanks for this! Noting that line 708 just above that can be removed as well:

`(stackerAtCycle (get-stacker-at-cycle-or-default targetCycle stackerId))`

The only place that map is used is to get the values for `amountStacked` and `toReturn`.
