### ISSUE TITLE
Add supply cap

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#17]
As commented [here](https://github.com/citycoins/citycoin/issues/6#issuecomment-831436597), there should be a supply cap.

**Comment by whoabuddy** [comment]
I think I want to push back against that idea. Mining is the main function that funds the city bag, so it should be able to continue indefinitely, although it may be worth halving the rate to something lower than 125 per block.

Based on my estimations, 125 per block wouldn't raise the total amount of coins by much, curious to hear what others have to say here:

Time in Blocks | Reward | Total Circulating Supply | Year | Notes
-- | -- | -- | -- | --
10,000 | 2,466 | 24,660,000 | 2021 | similar to STX mining bonus
165,000 | 1,000 | 189,660,000 | 2021 | current height 5/1/2021 681,403
375,000 | 500 | 294,660,000 | 2024 | estimated 3/16/2024
585,000 | 250 | 347,160,000 | 2028 | estimated 2028
795,000 | 125 | 373,410,000 | 2032 | estimated 2032, continues forever
1,005,000 | 125 | 399,660,000 | 2036 | estimated 2036
1,215,000 | 125 | 425,910,000 | 2040 | estimated 2040

**Comment by whoabuddy** [comment]
Closing this in favor of indefinite continuation per the [issuance schedule in PRD](https://github.com/citycoins/citycoin/blob/main/citycoin-prd.md#issuance-schedule).
