### ISSUE TITLE
SIP 010 is out of date

### ISSUE THREAD

**Issue by jcnelson** [citycoins/citycoin#22]
The latest SIP 010 trait includes a token memo.

**Comment by whoabuddy** [comment]
Is this official yet?

**Comment by 314159265359879** [comment]
> 
> 
> Is this official yet?

I don't think it is. I would expect confirmation here:
https://github.com/stacksgov/sips/pull/25

And after deployment we should also change the link under "activation" here asap:
https://github.com/stacksgov/sips/blob/hstove-feat/sip-10-ft/sips/sip-010/sip-010-fungible-token-standard.md

Also not yet shown here
https://search-clarity.dev/?declare=&use=&search=sip-010-trait

**Comment by jcnelson** [comment]
It's not ratified until there are at least 5 implementations, but that shouldn't stop you from using it.  I pinged the SIP authors, but don't let them block you -- strictly speaking, you don't need to include `impl-trait` in your contract in order for your contract to implement the trait (however, it would be best to test with `impl-trait` to make sure your contract faithfully implements the interface even if it's not yet on mainnet).
