### ISSUE TITLE
Redundant `asserts!`, that will always pass if executed.

### ISSUE THREAD

**Issue by LNow** [citycoins/citycoin#25]
I believe that following `asserts!` can be safely removed as it will never throw an error.
https://github.com/citycoins/citycoin/blob/18e0d76083425465222e957ae9cf08f8ffa7b9c4/contracts/citycoin.clar#L401-L402

**Reasoning**
Values used in this check are calculated as follows:
|variable|calculation|
|-|-|
|cur-reward-cycle| (get-reward-cycle now-stacks-ht)|
|start-reward-cycle| (+ u1 (get-reward-cycle start-stacks-ht))|

1.  If `now-stacks-ht` is not smaller than `start-stacks-ht`, condition above the one mentioned in this issue will catch that and throw an error.
https://github.com/citycoins/citycoin/blob/18e0d76083425465222e957ae9cf08f8ffa7b9c4/contracts/citycoin.clar#L398-L399
2.  If `now-stacks-ht` is smaller than `start-stacks-ht` and both falls into the same reward cycle, thanks to `+ u1` `start-reward-cycle` will always be greater than `cur-reward-cycle` by 1
3. If `now-stacks-ht` is smaller than `start-stacks-ht` and they falls into two different reward cycles,  `start-reward-cycle` will always be greater than `cur-reward-cycle` by at least 2.

@whoabuddy, @asteriabtc, @friedger, can you please double check above?

**Comment by asteriabtc** [comment]
yep. lgtm! it will always pass in this case.
