### ISSUE TITLE
Add message to miner registration

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#38]
Similar to the message in the genesis block, let's set it up so that when signaling for activation, you can leave a short message written on chain along with the registration. 📝

**Comment by whoabuddy** [comment]
Are emojis supported?

**Comment by friedger** [comment]
Can all 20 miners leave a message?

**Comment by whoabuddy** [comment]
That was the idea, to give them a chance to write something on-chain while signaling activation.
