### ISSUE TITLE
Make/put metadata.json and logo on cdn for citycoins.co

### ISSUE THREAD

**Issue by 314159265359879** [citycoins/citycoin#40]
I did not see a dedicated place for static files such as we use on x.syvita.org (Content Delivery Network) I think @asteriabtc can advise on this for citycoins.co. I have made some draft metadata JSON's those should eventually be hosted there together with the logo you want it to point to.

**Comment by asteriabtc** [comment]
We can just add this to X and use that. Will work great

**Comment by 314159265359879** [comment]
> 
> 
> We can just add this to X and use that. Will work great

In that case the link to the metadata JSON and link to the image would start with
https://x.syvita.org/...

In my example I suggested
https://cdn.citycoins.co/...

From the brand perspective using the citycoins.co domain makes a lot of sense. I guess we could still use the later with a redirect to stick with the brand, yet use the shared cdn?

**Comment by whoabuddy** [comment]
@314159265359879 Thanks for this! I was going to create an issue for it and you already beat me to the punch 🙂 👊 

@asteriabtc I like the idea of the link pointing to https://cdn.citycoins.co, I'll touch base with you in DM on the configuration.

**Comment by whoabuddy** [comment]
Cherry-picked the commits and uploaded both files to the cdn repo, thanks for this!
