### ISSUE TITLE
Split miner commits

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin#5]
- custodied wallet keys are only accessible to the respective city (mayor, treasurer, etc)
- if Stacking is active:
  - 70% of the miner commits are distributed to Stackers of the citycoin
  - 30% of the miner commits are distributed to the custodied wallet for the city ("THE BAG")
- if Stacking is not active:
  - 100% of the miner commits are distributed to the custodied wallet for the city ("THE BAG")

**Comment by whoabuddy** [comment]
One note to add here, the recommendations above are what we want to use with the MVP (70%/30%), but these should be constants or outlined in a way that's easy to change for future implementations.

**Comment by pxydn** [comment]
> One note to add here, the recommendations above are what we want to use with the MVP (70%/30%), but these should be constants or outlined in a way that's easy to change for future implementations.

yes, these are currently constants at the top of my local contract 🔥
