### ISSUE TITLE
Add ability to change city principal

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#51]
Not your keys, not your coins. The private key should be protected at all costs, and is the key to the city's funds.

But, what if the city changes custody providers, how can they guarantee custody provider A burned the key?

What if they want to switch to a multi-sig wallet for added security?

There could be a public function in which the defined principal (and only the defined principal) can change the principal for `city-wallet`.

Thoughts?

**Comment by hstove** [comment]
Put another way, if this functionality is added, then custody of miner spends will be forever stuck in a single address. Whoever is the first custodian is the permanent custodian. The only way you could change custody is by transferring the private key to a new custodian. In that case, it's never possible to be sure that the original custodian burned their copy of the private key.

**Comment by LNow** [comment]
This is quite easy change to implement.

The only question I have is : Who should have the power to change city' s address? Contract owner/deployer? Maybe city itself?

**Comment by hstove** [comment]
IMO only the custodian address should be able to change the custodian address

**Comment by hstove** [comment]
There are so many cool things you could do with this feature... 

You could have the city wallet be a smart contract. The smart contract could have governance (with the citycoin), which allows for some % of funds to be used as voted via governance. While still maintaining the ability for the city to fully control funds

**Comment by whoabuddy** [comment]
Yes, the custodied address not the contract owner, and the more I've thought about this it definitely makes sense to have. Thanks @hstove for bringing it up and some possible use cases! Excited to see how things evolve! 😁

**Comment by LNow** [comment]
OK, I prepared PR that allows city wallet custodian to change it to a different one.
@hstove if you have more ideas or any concerns with regards to features we already build - feel free to open an issue or reach us on discord.
