### ISSUE TITLE
Add function for inflows to Stackers

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#63]
Stacks miners receive coinbase rewards and fees for transactions on the Stacks blockchain, with the latter becoming the main source of income over time. There should be a function that allows for the inflow of CityCoins to Stackers, so that a separate smart contract could operate by collecting fees and distributing them in a similar mechanism.

**Comment by LNow** [comment]
Collecting such fees can happen only when someone will call `transfer` function of our FT.
It means that we have to implement such functionality in main contract or wrap it with secondary contract.

**Comment by whoabuddy** [comment]
If this were possible in a secondary contract that'd be ideal, trying to add as little code as possible, but inspired from an idea that Balaji had about monetizing a smart contract interface. Imagine a Freehold that pays out in MiamiCoin for tasks, but when they make payouts, they send a small percentage to MiamiCoin stackers.

This one is probably ambitious for V1, but a thought I wanted to get documented at the very least.

**Comment by hstove** [comment]
In the idea of Freehold paying MIA and some going to MIA stackers - you could write a contract that holds part of the MIA from freehold, and then have logic that allows stackers to claim their portion of that bucket. You could do this with the `at-block` fn to ensure that the address was stacking at that moment in time. Or you could simply check their balance at that point in the past - allowing any MIA holder to claim it

It would be hard/impossible to do a bulk payout to all MIA stackers, especially if there are many. IMO its much more straightforward and standard to allow for "claimable" rewards.

I'm no tax expert, but there are also tax advantages to claimed rewards vs. directly received rewards.

**Comment by whoabuddy** [comment]
Closing this out based on @hstove suggestion of making it claimable through a mechanism like `at-block`, which would be out of scope for this repo.

I like this idea, though, and hope to see more smart contracts built *around* CityCoins as time goes on :sunglasses:
