### ISSUE TITLE
Deploy to testnet

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#65]
It's time to start testing!

In order to close out #8 and #10 we need to do some stress testing, which requires the latest version of contract code to be deployed the testnet and the UI updated to use the new contract address.

Some considerations to help with testing:

- reduce token-reward-maturity: u100 to u10 (~1.6hrs)
- reduce reward-cycle-length: u2100 to u100 (~16hrs)
- reduce activation threshold to u5 registrants
- reduce mining activation delay to u10 blocks
- update SIP-010 trait to testnet version

**Comment by whoabuddy** [comment]
Updated deployment for testing:
https://explorer.stacks.co/txid/0x7dc6598b12940715c94ea13acbb09647c5840117d12ca34df4e2e8ed6097272f?chain=testnet

**Comment by 314159265359879** [comment]
Should this be working? I am trying to call the "register-miner" function with the Explorer Sandbox. 
![image](https://user-images.githubusercontent.com/33360391/121404500-4ebb3d00-c95c-11eb-932c-02ae3675962d.png)

**Comment by whoabuddy** [comment]
I believe that's an issue with how the sandbox submits transactions, I ran into something similar in earlier versions.

In addition, mining must be activated first (although if this were successful, you would receive the related error).

**Comment by 314159265359879** [comment]
calling min-tokens-over-30-blocks does go through. I expect that it will fail because I can not currently set post conditions I need on the Sandbox transaction.

**Comment by 314159265359879** [comment]
> 
> 
> I believe that's an issue with how the sandbox submits transactions, I ran into something similar in earlier versions.

Yes I have also seen it more lately, thanks.

**Comment by whoabuddy** [comment]
Due to instabilities on testnet, updated the issue to reflect we are moving toward a regtest deployment similar to that of Arkadiko.

Steps that remain:

- deploy contract to regtest network
- develop [similar docs to Arkadiko](https://docs.arkadiko.finance/) starting with regtest specifics for testing
- docs can then expand to a separate resource to citycoins.co

**Comment by whoabuddy** [comment]
Latest versions are successfully deployed to testnet! :tada: :partying_face: 

1. [citycoin-vrf](https://explorer.stacks.co/txid/0xd78700a91ad0ab86deeb41608ce248915a19598d680a92d958f1c011c7557ace)
2. [citycoin-core-trait](https://explorer.stacks.co/txid/0x7af881046c4d94a9b53405069a63a4ecaf7a18734b3e78387d553038ecf07cdb)
3. [citycoin-token-trait](https://explorer.stacks.co/txid/0xe2dc32f2d88399af1b3b77693d5181335d04adcb060483213daa438cb1385fda)
4. [citycoin-auth](https://explorer.stacks.co/txid/0x5529ab67930773ad06f22618b0e02705fa7c010deaedc348517983c3be12f172)
5. [sip-010-trait-ft-standard](https://explorer.stacks.co/txid/0x08cb05b2ecc3ffc67d5391d338314a89d53818917c6ba42090fe1a02681d3620)
6. [citycoin-token](https://explorer.stacks.co/txid/0x6c2c95a2404199a2ff0e8372d39cdf1be06f5ce1173b680a56dfdf27467ab6b2)
7. [citycoin-core-v1](https://explorer.stacks.co/txid/0xabe73ff71f72d8a8388e9834613789f1ce1ebf1a7c96c97166eeec8f81f1b139)

The `citycoin-auth` contract accepted the [initialize contracts](https://explorer.stacks.co/txid/0x92b1a8dfe286a8591ed935640e484df9ad9fd13b4773cebb82229b08fe0eb6e8) call so we are ready for miners to begin registration.

**Please note** the changes at the top of this issue regarding lowered/accelerated thresholds.

UI updates coming next! :champagne:
