### ISSUE TITLE
Add versioning system to allow for future code revisions

### ISSUE THREAD

**Issue by SyAsteria** [citycoins/citycoin#7]
- use getters around all map data and use at-block as a pointer
- e.g. if 2.0 is deployed, 1.0 miners should still be able to claim rewards
- e.g. if block is from 1.0 era, then use at-block to get map from old contract

**Comment by whoabuddy** [comment]
this is also a good practice for data-vars!

**Comment by friedger** [comment]
Can you clarify the requirements? This requires a base contract that defines the current valid version. Do we want that?

**Comment by asteriabtc** [comment]
might wanna use something like what the prototype [Syvita Kernel](https://github.com/syvita/kernel) is working on

it's what we're planning to use for DAO versioning, and could be adapted with slight changes to the voting mechanism for individual CityCoins.
