### ISSUE TITLE
Add read-only API functions for off-chain apps

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin#8]
- will serve as data source for future contracts or tools
- will allow for recreation of experiences like stxmining.club and stacking.club

**Comment by whoabuddy** [comment]
Need to review this against #10 and [Statistics heading in the PRD](https://github.com/citycoins/citycoin/blob/main/citycoin-prd.md#usability) before mainnet deployment.

**Comment by friedger** [comment]
There are already quite a few read-only functions. Are there any missing?

**Comment by whoabuddy** [comment]
I just added a few more in #58, but most of the data points are covered.

**Comment by whoabuddy** [comment]
Closing this one out as we have plenty of code packed in there, can reopen for individual functions as needed.
