### ISSUE TITLE
Extract token code into separate contract

### ISSUE THREAD

**Issue by LNow** [citycoins/citycoin#83]
Right token code is in the same contract as mining and stacking code. This approach has the undeniable advantage of making it easy to write code that uses the token, but it makes impossible to upgrade code without wrapping token with additional layer.

To mitigate this problem, we should extract all token code (including SIP-010 functions) into separate contract and add to it dedicated minting function that can be called only by selected contract addresses.

Securing this new function can be done in a similar fashion as it has been implemented by Stacks team in POX contract (see details below).
Of course we gonna have to tailor it to our needs, but overall it is almost exactly what we need.

We have to think about who should (person/organization/contract) should have the power to add or remove contracts to and from the allowance list. We need to think through all options, therefore for now I suggest to give this power to contract deployer and once we decide how to do it correctly, then we'll make proper amendments.

---
**Security mechanism used in POX contract:**
Map definition: [>>LINK<<](https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/boot/pox.clar#L86-L89)
Security function: [>>LINK<<](https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/boot/pox.clar#L183-L193)
Adding contract to allowance list: [>>LINK<<](https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/boot/pox.clar#L417-L423)
Removing contract from allowance list: [>>LINK<<](https://github.com/blockstack/stacks-blockchain/blob/85f07f1aa74638458ac118627477d05936994841/src/chainstate/stacks/boot/pox.clar#L407-L411)

**Comment by whoabuddy** [comment]
> We have to think about who should (person/organization/contract) should have the power to add or remove contracts to and from the allowance list.

That's the big question! I'm all for separating the token for reasons identified above, but I do not want to assign a single entity control over this process as it defeats the goal of a truly fair and decentralized operation. We could do it for initial testing, but we would need to fast-track a solution to this as it would be a launch blocker at that point.

That being said, I know @philipdesmedt has set up a lot of connected contracts and an upgrade system through traits, and we may be able to leverage some of the techniques [used by the Arkadiko contracts](https://github.com/arkadiko-dao/arkadiko/tree/master/clarity/contracts). This may be more relevant in #84.

We also may be able to allow for this type of update to come from the custodied wallet address, same as updating their own STX address, but it's not immediately clear to me that they would be the best ones to bear the responsibility.

**Comment by philipdesmedt** [comment]
We use the DAO (which never changes, can only be deployed once and thus is very lean) which keeps a map of smart contracts (name -> principal) that are registered with the protocol, see https://github.com/arkadiko-dao/arkadiko/blob/master/clarity/contracts/arkadiko-dao.clar#L155

Not sure if this is the best solution, but works for us :)

**Comment by LNow** [comment]
@whoabuddy if we decide that it needs to be done using some form of decentralized process, then we have to be prepare to jump into rabbit hole called DAO. Figure out who should be able to vote, how voting process should look like, how to set pass/loss threshold, who should have power to open up such voting and set threshold etc. 
As much as I like the idea of making it a decentralized I'm worried that we won't have enough time to do this correctly.

With regards to mechanics used in Arkadio - we can borrow from @philipdesmedt his implementation of securing function calls :)
Core concept is similar to what can be found in PoX, but details are a bit different.

**Comment by whoabuddy** [comment]
@LNow I agree, I'd like to keep it as simple as possible and had an idea that ties into activating #84 through mining memos. 

1. A new contract version is created and deployed
2. The city wallet adds the new contract to the approved contract list in the minting contract, but as inactive status
2. The miners vote for the upgrade [using the memo](https://github.com/citycoins/citycoin/issues/84#issuecomment-863205610) to activate the new contract
3. Once threshold is reached:
    - new contract enters active status in minting contract and is available
    - sunset/prepare phases begin between v1 to v2 as part of upgrade process

This way the city can add a new contract but miners have to approve and activate it.

On that 4th step there may be some timing to consider, but as long as we set decent thresholds and follow Stacks block heights as the measuring stick, I think it will be fine.

**Comment by LNow** [comment]
I have to think about details of 2nd and 3rd step and will present my thoughs about it in #84
