### ISSUE TITLE
 Add function to claim mining rewards for several blocks at once

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#87]
Claiming block rewards one by one is annoying.

See also https://github.com/citycoins/citycoin-ui/issues/24

**Comment by whoabuddy** [comment]
Yes, I think this was in part due to execution costs, same with how mining is limited to 30 blocks at a time but we can revisit to make sure.

**Comment by LNow** [comment]
We can reduce execution costs of single claim that right now is in range 4.27% - 6.67% to something like 2.07% - 6.69%.
It will increase deployment costs a little bit, but we do deployments only once so I think it is worth to do it.

Claiming rewards for several blocks at once would be possible, but number of blocks won't be high. Probably no more than 10.

**Comment by whoabuddy** [comment]
Noting that after the 2.0.5 upgrade this may be possible through a proxy contract using the core contract trait. Definitely needs some cost testing but I think it'd be a fun experiment!

**Comment by whoabuddy** [comment]
Closing this out as this is possible through a separate contract, and there is already one such mainnet implementation for NYC:

https://explorer.stacks.co/txid/SPW7EPC9JR87GFETCD7T1BDWDYN5WAZ0NV667817.claim-many?chain=mainnet
