### ISSUE TITLE
Current stacks height in get-entitled-stacking-reward can be any value

### ISSUE THREAD

**Issue by friedger** [citycoins/citycoin#88]
In `get-entitled-stacking-reward`, the parameter cur-block-height can be anything. There should be a comment that the result is incorrect if called with anything else than the current stack block height.

**Comment by LNow** [comment]
How about making it private and create a new read-only function with simplified signature? 
For example:
```lisp
(define-read-only (get-stacking-reward (stacker principal) (reward-cycle uint))
   (get-entitled-stacking-reward stacker reward-cycle block-height)
)
```
