### ISSUE TITLE
Develop initial web UI for miners

### ISSUE THREAD

**Issue by asteriabtc** [citycoins/citycoin#9]
- [ ] a miner can submit STX to the contract using the Stacks Web Wallet
- [ ] a miner can choose to submit for one or multiple blocks at a given rate
- [ ] a miner can see available citycoin rewards and claim them
- [ ] a miner can see their mining history, stored in Gaia (TBF)

**Comment by whoabuddy** [comment]
Closing in favor of combined topic in #10
