### ISSUE TITLE
`claim-stacking-reward` fails if no STX entitled to caller

### ISSUE THREAD

**Issue by whoabuddy** [citycoins/citycoin#99]
## Describe the Problem

The `claim-stacking-reward` function fails if there are no STX entitled to the user.

https://github.com/citycoins/citycoin/blob/bf7e22ff8bf29f74a0a5a60c5b0737c2d1cd18f3/contracts/citycoin.clar#L954-L962

This does not cover the edge cases of two situations:

- no miners mining, so no STX rewarded
- stacked amount so small, entitled to less than 1 uSTX

And results in the user's tokens getting locked in the contract with no way to redeem.

## Example

Call `get-entitled-stacking-reward` with the following parameters:

- stacker: ST3CK642B6119EVC6CT550PW5EZZ1AJW6608HK60A
- target-reward-cycle: 9
- cur-block-height: 16470

Result: `u0`

Call `get-stacked-in-cycle` with the following parameters:

- stacker: ST3CK642B6119EVC6CT550PW5EZZ1AJW6608HK60A
- reward-cycle: 9

Result: `u1500000`

Trying to redeem this fails with `u10 ERR-NOTHING-TO-REDEEM`, see example TX below.

https://explorer.stacks.co/txid/0xa3c7d6abfa36a0ff4717a4bc8a4bd6b359b6877517618c454b548b0d1c4a65db?chain=testnet

## Possible Fix

The function should check if either `entitled-ustx` OR `stacked-in-cycle` are positive values and handle the transfers accordingly.

**Note:** this may affect how the post conditions are specified in citycoins/citycoin-ui#47.

**Comment by LNow** [comment]
We can try do it like this:

```clarity
(define-public (claim-stacking-reward (target-reward-cycle uint))
    (let (
        (stacker tx-sender)    
        (entitled-ustx (get-entitled-stacking-reward tx-sender target-reward-cycle block-height))
        (stacked-in-cycle (get-stacked-in-cycle tx-sender target-reward-cycle))
    )
    (begin
        (asserts! (> (get-reward-cycle block-height) target-reward-cycle)
            (err ERR-CYCLE-NOT-COMPLETED))

        (asserts! (> stacked-in-cycle u0)
            (err ERR-NOT-STACKED-IN-CYCLE))

        ;; If we reach this point we know that 
        ;;  1) user want to claim reward for cycle that is already completed
        ;;  2) user stacked at least 1 token so we have to send it back
        
        ;; disable possibility to claim again
        (map-set stacked-per-cycle
            { stacker: tx-sender, reward-cycle: target-reward-cycle }
            { amount-token: u0 })

        ;; send back tokens stacked by user
        (try! (as-contract (contract-call? .token transfer stacked-in-cycle tx-sender stacker none)))

        ;; if user stacked enough tokens to be eligibl to claim ustx - send it to him/her
        (if (> entitled-ustx u0)
            (try! (as-contract (stx-transfer? entitled-ustx tx-sender stacker)))
            true    
        )

        (ok true)
    ))
)
```

**Comment by friedger** [comment]
Currently, `claim-stacking-rewards` has the side effect that it unstacks tokens. I think we should have one function to just claim the reward and then more functions to `claim-and-unstack` and to `claim-all-rewards-and-unstack`.

Related to #100 (bug about unstacking several times) and #87 (claiming for miner rewards for several blocks)

**Comment by whoabuddy** [comment]
@friedger I'm capturing these comments in a new issue so they don't get lost!
